import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head";
import ContenidoPrincipal from "@/components/ContenidoPrincipal";
import ApolloWrapper from "@/config/ApolloWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "CRM - clientes Nextjs 14",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
        <ApolloWrapper>
          <ContenidoPrincipal>{children}</ContenidoPrincipal>
        </ApolloWrapper>
      </body>
    </html>
  );
}
